version: '2.1'
services:
    nats:
        image: autopilotpattern/nats:0.9.6-r1.0.0
        restart: always
        links:
          - consul:consul
        expose:
          - 4222
          - 6222
          - 8222
        environment:
          - CONSUL_AGENT=1
          - CONSUL=consul
    consul:
        image: autopilotpattern/consul:0.7.2-r0.8
        command: >
          /usr/local/bin/containerpilot
          /bin/consul agent -server
            -bootstrap
            -config-dir=/etc/consul
            -ui-dir /ui
            -client=0.0.0.0
        restart: always
        mem_limit: 128m
        ports:
          - "8500:8500"
    natsboard:
        build: ./
        links:
          - consul:consul
        ports:
          - "3000:3000"
        environment:
          - CONSUL=consul
          - CONSUL_AGENT=1
